<?php

namespace Database\Seeders;

use App\Models\PettyCash;
use Illuminate\Database\Seeder;

class PettyCashSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['date' => '2025-11-29', 'amount' => 20000, 'availability' => null, 'expense_type' => 'Maintenance', 'expense_paid' => 0, 'payment_method' => 'Cash', 'cleared_by' => 'HDFC Bank Ltd', 'vendor_name' => null, 'expense_details' => 'Petty cash', 'remark' => 'Maintainance purpose', 'expense_category' => 'Maintenance', 'is_withdrawal' => true],
            ['date' => '2025-11-29', 'amount' => null, 'availability' => 'Yes', 'expense_type' => 'Maintenance', 'expense_paid' => 5139, 'payment_method' => 'Cash', 'cleared_by' => null, 'vendor_name' => 'Pankaj Wani', 'expense_details' => 'Water pump repair', 'remark' => 'Paid to Pankaj Wani for water pump repair (345+3200+544+1050)', 'expense_category' => 'Maintenance', 'is_withdrawal' => false],
            ['date' => '2025-11-30', 'amount' => null, 'availability' => 'No', 'expense_type' => 'Maintenance', 'expense_paid' => 7500, 'payment_method' => 'Cash', 'cleared_by' => null, 'vendor_name' => 'Narendra halabe', 'expense_details' => 'Electrical work', 'remark' => 'Paid to Narendra halabe for electrical work', 'expense_category' => 'Maintenance', 'is_withdrawal' => false],
            ['date' => '2025-12-05', 'amount' => null, 'availability' => 'No', 'expense_type' => 'Maintenance', 'expense_paid' => 1250, 'payment_method' => 'Cash', 'cleared_by' => null, 'vendor_name' => 'Vinayak Bhondve', 'expense_details' => 'Drainage work', 'remark' => 'Paid to Vinayak Bhondve B wing for Drainage work', 'expense_category' => 'Maintenance', 'is_withdrawal' => false],
            ['date' => '2025-12-15', 'amount' => null, 'availability' => 'Yes', 'expense_type' => 'Maintenance', 'expense_paid' => 50, 'payment_method' => 'Cash', 'cleared_by' => null, 'vendor_name' => 'Xerox Noc', 'expense_details' => 'Xerox', 'remark' => 'Paid to Xerox Noc for 1110', 'expense_category' => 'Maintenance', 'is_withdrawal' => false],
            ['date' => '2025-12-20', 'amount' => null, 'availability' => 'No', 'expense_type' => 'Maintenance', 'expense_paid' => 1000, 'payment_method' => 'Cash', 'cleared_by' => null, 'vendor_name' => null, 'expense_details' => 'Housekeeping', 'remark' => 'Paid to housekeeping D wing terrace cleaning', 'expense_category' => 'Maintenance', 'is_withdrawal' => false],
            ['date' => '2025-12-22', 'amount' => null, 'availability' => 'No', 'expense_type' => 'Maintenance', 'expense_paid' => 5774, 'payment_method' => 'Cash', 'cleared_by' => null, 'vendor_name' => 'Vinayak Bhondve', 'expense_details' => 'New water connection', 'remark' => 'Paid to Vinayak Bhondve B wing for New water connection', 'expense_category' => 'Maintenance', 'is_withdrawal' => false],
            ['date' => '2025-12-24', 'amount' => 20000, 'availability' => null, 'expense_type' => 'Maintenance', 'expense_paid' => 0, 'payment_method' => 'Cash', 'cleared_by' => 'HDFC Bank Ltd', 'vendor_name' => null, 'expense_details' => 'Petty cash', 'remark' => 'Maintainance purpose', 'expense_category' => 'Maintenance', 'is_withdrawal' => true],
            ['date' => '2025-12-24', 'amount' => null, 'availability' => 'No', 'expense_type' => 'Maintenance', 'expense_paid' => 300, 'payment_method' => 'Cash', 'cleared_by' => null, 'vendor_name' => 'Electrician', 'expense_details' => 'Motor starter wiring repair', 'remark' => 'Paid to Electrician for motor starter wiring repair', 'expense_category' => 'Miscellaneous', 'is_withdrawal' => false],
            ['date' => '2025-12-24', 'amount' => null, 'availability' => 'No', 'expense_type' => 'Maintenance', 'expense_paid' => 350, 'payment_method' => 'Cash', 'cleared_by' => null, 'vendor_name' => 'Electrician', 'expense_details' => 'Motor starter fittment', 'remark' => 'Paid to Electrician starter motor fittment', 'expense_category' => 'Miscellaneous', 'is_withdrawal' => false],
            ['date' => '2025-12-24', 'amount' => null, 'availability' => 'Yes', 'expense_type' => 'Maintenance', 'expense_paid' => 4070, 'payment_method' => 'Cash', 'cleared_by' => null, 'vendor_name' => null, 'expense_details' => 'Motor starter', 'remark' => 'Purchase of motor starter', 'expense_category' => 'Miscellaneous', 'is_withdrawal' => false],
            ['date' => '2025-12-24', 'amount' => null, 'availability' => 'Yes', 'expense_type' => 'Maintenance', 'expense_paid' => 50, 'payment_method' => 'Cash', 'cleared_by' => null, 'vendor_name' => null, 'expense_details' => 'Xerox', 'remark' => 'Xerox mseb letter', 'expense_category' => 'Miscellaneous', 'is_withdrawal' => false],
            ['date' => '2026-01-01', 'amount' => null, 'availability' => 'No', 'expense_type' => 'Maintenance', 'expense_paid' => 1027, 'payment_method' => 'Cash', 'cleared_by' => null, 'vendor_name' => 'Vinayak Bhondve', 'expense_details' => 'Pipeline charges', 'remark' => 'Paid to Vinayak Bhondve B wing for Pipeline charges', 'expense_category' => 'Miscellaneous', 'is_withdrawal' => false],
            ['date' => '2026-01-03', 'amount' => null, 'availability' => 'Yes', 'expense_type' => 'Maintenance', 'expense_paid' => 19, 'payment_method' => 'Cash', 'cleared_by' => null, 'vendor_name' => null, 'expense_details' => 'Xerox', 'remark' => 'Xerox', 'expense_category' => 'Miscellaneous', 'is_withdrawal' => false],
            ['date' => '2026-01-20', 'amount' => null, 'availability' => 'Yes', 'expense_type' => 'Maintenance', 'expense_paid' => 3380, 'payment_method' => 'Cash', 'cleared_by' => null, 'vendor_name' => null, 'expense_details' => 'Stationary', 'remark' => 'Stationary purchased by auditor', 'expense_category' => 'Miscellaneous', 'is_withdrawal' => false],
            ['date' => '2026-02-14', 'amount' => null, 'availability' => 'Yes', 'expense_type' => 'Maintenance', 'expense_paid' => 5000, 'payment_method' => 'Cash', 'cleared_by' => null, 'vendor_name' => null, 'expense_details' => 'Drainage cleaning', 'remark' => 'Drainage cleaning work', 'expense_category' => 'Miscellaneous', 'is_withdrawal' => false],
            ['date' => '2026-02-17', 'amount' => null, 'availability' => 'No', 'expense_type' => 'Maintenance', 'expense_paid' => 4618, 'payment_method' => 'Cash', 'cleared_by' => null, 'vendor_name' => 'Vinayak Bhondve', 'expense_details' => 'Pipeline leakage maintenance', 'remark' => 'Paid to Vinayak Bhondve B wing water for pipeline leakage maintenance', 'expense_category' => 'Miscellaneous', 'is_withdrawal' => false],
            ['date' => '2026-02-21', 'amount' => 20000, 'availability' => null, 'expense_type' => 'Maintenance', 'expense_paid' => 0, 'payment_method' => 'Cash', 'cleared_by' => 'HDFC Bank Ltd', 'vendor_name' => null, 'expense_details' => 'Petty cash', 'remark' => 'Maintenance', 'expense_category' => 'Maintenance', 'is_withdrawal' => true],
            ['date' => '2026-02-21', 'amount' => null, 'availability' => 'Yes', 'expense_type' => 'Maintenance', 'expense_paid' => 445, 'payment_method' => 'Cash', 'cleared_by' => null, 'vendor_name' => null, 'expense_details' => 'Locks and plumbing materials', 'remark' => 'Locks and plumbing materials', 'expense_category' => 'Miscellaneous', 'is_withdrawal' => false],
            ['date' => '2026-02-21', 'amount' => null, 'availability' => 'Yes', 'expense_type' => 'Maintenance', 'expense_paid' => 1900, 'payment_method' => 'Cash', 'cleared_by' => null, 'vendor_name' => 'Ganesh Jadhav', 'expense_details' => 'Plumbing expenses', 'remark' => 'Plumbing expenses (to ganesh jadhav)', 'expense_category' => 'Miscellaneous', 'is_withdrawal' => false],
            ['date' => '2026-02-21', 'amount' => null, 'availability' => 'Yes', 'expense_type' => 'Maintenance', 'expense_paid' => 3380, 'payment_method' => 'Cash', 'cleared_by' => null, 'vendor_name' => 'Kalpesh Shirode', 'expense_details' => 'Lift mats', 'remark' => 'Lift mats (to kalpesh shirode)', 'expense_category' => 'Miscellaneous', 'is_withdrawal' => false],
            ['date' => '2026-02-28', 'amount' => null, 'availability' => 'No', 'expense_type' => 'Maintenance', 'expense_paid' => 260, 'payment_method' => 'Cash', 'cleared_by' => null, 'vendor_name' => null, 'expense_details' => 'Toilet cleaner', 'remark' => 'Toilet cleaner', 'expense_category' => 'Miscellaneous', 'is_withdrawal' => false],
            ['date' => '2026-02-28', 'amount' => null, 'availability' => 'No', 'expense_type' => 'Maintenance', 'expense_paid' => 700, 'payment_method' => 'Cash', 'cleared_by' => null, 'vendor_name' => null, 'expense_details' => 'Toilet feetings', 'remark' => 'Toilet feetings (to math dada)', 'expense_category' => 'Miscellaneous', 'is_withdrawal' => false],
            ['date' => '2026-02-28', 'amount' => null, 'availability' => 'No', 'expense_type' => 'Maintenance', 'expense_paid' => 1200, 'payment_method' => 'Cash', 'cleared_by' => null, 'vendor_name' => null, 'expense_details' => 'Toilet cleaning', 'remark' => 'Toilet cleaning', 'expense_category' => 'Miscellaneous', 'is_withdrawal' => false],
            ['date' => '2026-03-01', 'amount' => null, 'availability' => 'Yes', 'expense_type' => 'Maintenance', 'expense_paid' => 4300, 'payment_method' => 'Cash', 'cleared_by' => null, 'vendor_name' => null, 'expense_details' => 'Table and chair', 'remark' => 'Table n chair', 'expense_category' => 'Miscellaneous', 'is_withdrawal' => false],
            ['date' => '2026-03-07', 'amount' => 20000, 'availability' => null, 'expense_type' => 'Maintenance', 'expense_paid' => 0, 'payment_method' => 'Cash', 'cleared_by' => 'HDFC Bank Ltd', 'vendor_name' => null, 'expense_details' => 'Petty cash', 'remark' => 'Maintenance', 'expense_category' => 'Maintenance', 'is_withdrawal' => true],
            ['date' => '2026-03-07', 'amount' => null, 'availability' => 'No', 'expense_type' => 'Maintenance', 'expense_paid' => 3600, 'payment_method' => 'Cash', 'cleared_by' => null, 'vendor_name' => 'Vishal', 'expense_details' => 'Share certificate printing', 'remark' => 'Share certificate printing (to vishal)', 'expense_category' => 'Miscellaneous', 'is_withdrawal' => false],
            ['date' => '2026-03-15', 'amount' => null, 'availability' => 'Yes', 'expense_type' => 'Maintenance', 'expense_paid' => 2700, 'payment_method' => 'Cash', 'cleared_by' => null, 'vendor_name' => 'Vishal', 'expense_details' => 'Parking sticker', 'remark' => 'Parking sticker (to vishal)', 'expense_category' => 'Miscellaneous', 'is_withdrawal' => false],
            ['date' => '2026-03-16', 'amount' => null, 'availability' => 'Yes', 'expense_type' => 'Maintenance', 'expense_paid' => 5900, 'payment_method' => 'Cash', 'cleared_by' => null, 'vendor_name' => 'Pankaj Wani', 'expense_details' => 'Files', 'remark' => 'Files (to pankaj wani)', 'expense_category' => 'Miscellaneous', 'is_withdrawal' => false],
            ['date' => '2026-03-23', 'amount' => null, 'availability' => 'No', 'expense_type' => 'Maintenance', 'expense_paid' => 2455, 'payment_method' => 'Cash', 'cleared_by' => null, 'vendor_name' => 'Rupali Ghavte', 'expense_details' => 'Plumbing expenses', 'remark' => 'Plumbing expenses (to rupali ghavte)', 'expense_category' => 'Miscellaneous', 'is_withdrawal' => false],
        ];

        foreach ($data as $row) {
            PettyCash::create($row);
        }
    }
}
